name: 'Perl versions'
description: 'Generate Perl versions list for your matrix'
inputs:
  since-perl:
    description: "List all Perl versions since this (including this). See README for available versions and formats."
    type: string
    required: true
  until-perl:
    description: "List all Perl versions up to this (including this). See README for available versions and formats."
    type: string
    default: 'latest'
  with-devel:
    description: "Whether to include also 'devel' Perl"
    type: boolean
    default: false
  single-out:
    description: "Single out one version from the list. Values: exact version (e.g. 5.36), 'devel', 'oldest', 'newest', 'latest'. The singled-out version is excluded from perl-versions output."
    type: string
    required: false
  target:
    description: "Target platform: perl, perl-tester, macos, or windows-strawberry"
    type: string
    required: false
    default: "perl-tester"
outputs:
  perl-versions:
    description: "JSON containing list of perl versions"
  single-out:
    description: "The singled-out perl version (when single-out input is specified)"
runs:
  using: "node24"
  main: "dist/index.js"
