name: List perl versions

on:
  workflow_call:
    inputs:
      since-perl:
        description: "List Perl versions since given version (including)."
        type: string
        required: true
        default: "5.10"
      until-perl:
        description: "List all Perl versions up to this (including this). Example: 5.30"
        type: string
        required: false
      with-devel:
        description: "Whether to include also 'devel' Perl"
        type: boolean
        required: false
        default: false
    outputs:
      perl-versions:
        value: ${{ jobs.perl-versions.outputs.perl-versions }}

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: List perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - name: Perl versions action step
        id: action
        uses: perl-actions/perl-versions@main
        with:
          since-perl: ${{ inputs.since-perl }}
          until-perl: ${{ inputs.until-perl || null }}
          with-devel: ${{ inputs.with-devel || null }}

